name: Build OpenImageIO with vcpkg

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            triplet: x64-linux
          - os: windows-latest
            triplet: x64-windows
          - os: macos-latest
            triplet: x64-osx

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup vcpkg
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Cache vcpkg
      id: cache-vcpkg
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/vcpkg
          ./vcpkg
        key: vcpkg-${{ matrix.os }}-${{ matrix.triplet }}-${{ hashFiles('vcpkg.json') }}

    - name: Install vcpkg (Linux/macOS)
      if: matrix.os != 'windows-latest'
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.sh
        ./vcpkg integrate install
      shell: bash

    - name: Install vcpkg (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        .\bootstrap-vcpkg.bat
        .\vcpkg integrate install
      shell: cmd

    - name: Install OpenImageIO
      run: |
        ./vcpkg/vcpkg install openimageio[core,tools,opencolorio,pybind11]:${{ matrix.triplet }}
      shell: bash

    - name: Package artifacts including third-party libraries
      run: |
        mkdir -p artifacts
        cp -r vcpkg/installed/${{ matrix.triplet }} artifacts/openimageio-with-deps-${{ matrix.triplet }}
      shell: bash

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: openimageio-with-deps-${{ matrix.os }}-${{ matrix.triplet }}
        path: artifacts/openimageio-with-deps-${{ matrix.triplet }}
        retention-days: 7
