name: Build OpenImageIO with vcpkg

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            triplet: x64-linux
            compiler: gcc
          - os: windows-latest
            triplet: x64-windows
            compiler: msvc
          - os: macos-latest
            triplet: x64-osx
            compiler: gcc

    steps:
    - name: Debug Info
      run: |
        echo "Runner OS: ${{ runner.os }}"
        echo "Triplet: ${{ matrix.triplet }}"
        echo "Compiler: ${{ matrix.compiler }}"
        echo "Event: ${{ github.event_name }}"
        echo "Branch: ${{ github.ref_name }}"
      shell: bash

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install build dependencies (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y autoconf automake libtool pkg-config g++ gcc
      shell: bash

    - name: Install build dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install autoconf automake libtool pkg-config gcc
      shell: bash

    - name: Cache vcpkg
      id: cache-vcpkg
      uses: actions/cache@v4
      with:
        path: |
          ./vcpkg
          ./vcpkg/installed
        key: ${{ runner.os }}-vcpkg-${{ matrix.triplet }}-openimageio-${{ hashFiles('vcpkg.json') }}

    - name: Prepare vcpkg Directory (if cache miss)
      if: steps.cache-vcpkg.outputs.cache-hit != 'true'
      run: mkdir -p vcpkg
      shell: bash

    - name: Install vcpkg (Linux/macOS)
      if: matrix.os != 'windows-latest' && steps.cache-vcpkg.outputs.cache-hit != 'true'
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.sh
        ./vcpkg integrate install
      shell: bash
      env:
        CC: gcc
        CXX: g++

    - name: Install vcpkg (Windows)
      if: matrix.os == 'windows-latest' && steps.cache-vcpkg.outputs.cache-hit != 'true'
      shell: cmd
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        bootstrap-vcpkg.bat
        vcpkg integrate install

    - name: Install OpenImageIO
      run: |
        ./vcpkg/vcpkg install openimageio[core,tools]:${{ matrix.triplet }}
      shell: bash
      env:
        CC: ${{ matrix.os != 'windows-latest' && 'gcc' || '' }}
        CXX: ${{ matrix.os != 'windows-latest' && 'g++' || '' }}

    - name: Check for error logs
      if: failure()
      run: |
        if [ -f vcpkg/buildtrees/python3/autoconf-x64-linux-err.log ]; then
          echo "Autoconf error log:"
          cat vcpkg/buildtrees/python3/autoconf-x64-linux-err.log
        fi
      shell: bash

    - name: Package artifacts including third-party libraries
      if: matrix.os != 'windows-latest'
      run: |
        mkdir -p artifacts
        cp -r vcpkg/installed/${{ matrix.triplet }} artifacts/openimageio-with-deps-${{ matrix.triplet }}
        tar -czf openimageio-with-deps-${{ matrix.triplet }}.tar.gz -C artifacts openimageio-with-deps-${{ matrix.triplet }}
      shell: bash

    - name: Package artifacts including third-party libraries (Windows)
      if: matrix.os == 'windows-latest'
      shell: powershell
      run: |
        New-Item -ItemType Directory -Path artifacts -Force
        Copy-Item -Path vcpkg/installed/${{ matrix.triplet }} -Destination artifacts/openimageio-with-deps-${{ matrix.triplet }} -Recurse
        Compress-Archive -Path artifacts/openimageio-with-deps-${{ matrix.triplet }} -DestinationPath openimageio-with-deps-${{ matrix.triplet }}.zip -Force

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: openimageio-with-deps-${{ runner.os }}-${{ matrix.triplet }}
        path: openimageio-with-deps-${{ matrix.triplet }}.${{ matrix.os == 'windows-latest' && 'zip' || 'tar.gz' }}
        retention-days: 7