name: Build OpenImageIO with vcpkg

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            triplet: x64-linux
            compiler: gcc
          - os: windows-latest
            triplet: x64-windows
            compiler: msvc
          - os: macos-latest
            triplet: x64-osx
            compiler: gcc

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup vcpkg
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install build dependencies (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y autoconf automake libtool pkg-config g++ gcc
      shell: bash

    - name: Install build dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install autoconf automake libtool pkg-config gcc
      shell: bash

    - name: Cache vcpkg
      id: cache-vcpkg
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/vcpkg
          ./vcpkg
        key: vcpkg-${{ matrix.os }}-${{ matrix.triplet }}-${{ hashFiles('vcpkg.json') }}

    - name: Install vcpkg (Linux/macOS)
      if: matrix.os != 'windows-latest'
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        ./bootstrap-vcpkg.sh
        ./vcpkg integrate install
      shell: bash
      env:
        CC: gcc
        CXX: g++

    - name: Install vcpkg (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        .\bootstrap-vcpkg.bat
        .\vcpkg integrate install
      shell: cmd
      env:
        VCPKG_VISUAL_STUDIO_PATH: "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"

    - name: Install OpenImageIO
      run: |
        ./vcpkg/vcpkg install openimageio[core,tools,opencolorio,pybind11]:${{ matrix.triplet }}
      shell: bash
      env:
        CC: ${{ matrix.os != 'windows-latest' && 'gcc' || '' }}
        CXX: ${{ matrix.os != 'windows-latest' && 'g++' || '' }}

    - name: Check for error logs
      if: failure()
      run: |
        if [ -f vcpkg/buildtrees/python3/autoconf-x64-linux-err.log ]; then
          echo "Autoconf error log:"
          cat vcpkg/buildtrees/python3/autoconf-x64-linux-err.log
        fi
      shell: bash

    - name: Package artifacts including third-party libraries
      run: |
        mkdir -p artifacts
        cp -r vcpkg/installed/${{ matrix.triplet }} artifacts/openimageio-with-deps-${{ matrix.triplet }}
      shell: bash

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: openimageio-with-deps-${{ matrix.os }}-${{ matrix.triplet }}
        path: artifacts/openimageio-with-deps-${{ matrix.triplet }}
        retention-days: 7